namespace
{

enum genealsourcecode
{
	MUON, TPA, TPB, CALOMUON, TPC // general TPs
};

enum sourcecode
{
	CALO, MUONS, MUID, // muon...
	MUONSTPA, MUONSTPB, MUONSTPC, // muons chain TPs
	MUIDTPA, MUIDTPB, MUIDTPC // muid chain TPs
};

enum categorycodes
{
	MUONS3,
	MUONS2TPA1, MUONS2TPB1, MUONS2CALO1,
	MUONS1TPA2, MUONS1TPB2,
	MUONS1TPA1TPB1,
	MUONS0TPA3, MUONS0TPB3,
	MUONS0TPA2TPB1, MUONS0TPA2CALO1,
	MUONS0TPA1TPB2,
	
	MUID3,
	MUID2TPA1, MUID2TPB1, MUID2CALO1,
	MUID1TPA2, MUID1TPB2,
	MUID1TPA1TPB1,
	MUID0TPA3, MUID0TPB3,
	MUID0TPA2TPB1, MUID0TPA2CALO1,
	MUID0TPA1TPB2
};

}